/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/censor-detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["censor_detail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chart_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chart/multi-get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chart_multi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chart/stable-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stable_requests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chart/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chart_by_id"];
        put?: never;
        post?: never;
        delete: operations["delete_by_id"];
        options?: never;
        head?: never;
        patch: operations["chart_edit"];
        trace?: never;
    };
    "/chart/{id}/censor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["censor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chart/{id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["hide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chart/{id}/rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["my_rating"];
        put?: never;
        post: operations["rate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chart/{id}/set-ranked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["set_ranked"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chart/{id}/stabilize-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stabilize_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["collection_list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collection/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["collection_by_id"];
        put: operations["put_collection"];
        post?: never;
        delete: operations["delete_collection"];
        options?: never;
        head?: never;
        patch: operations["patch_collection"];
        trace?: never;
    };
    "/collection/{id}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_like_collection"];
        put?: never;
        post: operations["like_collection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collection/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["report_collection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dash/reviews/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dash_reviews_leaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dash/reviews/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dash/reviews/throughput": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dash_reviews_throughput"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dash/stables/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dash_stables_leaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dash/stables/profile-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["profile_all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dash/stables/throughput": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dash_stables_throughput"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dash/stables/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dash/users/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["active"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dash/users/registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["registration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edit/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["edit_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["user_edit"];
        trace?: never;
    };
    "/me/char": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_char"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/chars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_chars"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/subs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_subs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["edit_subs"];
        trace?: never;
    };
    "/oauth/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authorize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["get_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_app"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["record_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/record/best/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["best"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/record/get-pool/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_pool"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/record/list15/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list15"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/record/multi-get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["record_multi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/record/query/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["query"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/record/rks-update/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rks_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/record/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["record_by_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["staff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}/ban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ban_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}/ban-avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ban_avatar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}/ban-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ban_user_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["follow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["report_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}/update-roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["update_roles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActiveDay: {
            /** Format: date */
            date: string;
            /** Format: int64 */
            dau: number;
        };
        ActiveSeries: {
            series: components["schemas"]["ActiveDay"][];
        };
        AuthorizeR: {
            code: string;
            location: string;
            state: string;
        };
        BestR: {
            /** Format: float */
            accuracy: number;
            fullCombo: boolean;
            /** Format: int32 */
            score: number;
        };
        CensorBlock: {
            censored: boolean;
            text: string;
        };
        CensorP: {
            censor: boolean;
        };
        CensorRenderedP: {
            text: string;
        };
        Character: {
            artist: string;
            baseline: boolean;
            designer: string;
            id: string;
            illu_adjust: number[];
            illust: string;
            intro: string;
            name: string;
            /** Format: float */
            name_size?: number | null;
        };
        ChartView: {
            /** Format: date-time */
            chartUpdated: string;
            charter: string;
            composer: string;
            /** Format: date-time */
            created: string;
            description?: string | null;
            /** Format: float */
            difficulty: number;
            file: string;
            /** Format: int32 */
            id: number;
            illustration: string;
            illustrator: string;
            level: string;
            name: string;
            preview: string;
            ranked: boolean;
            /** Format: float */
            rating?: number | null;
            /** Format: int32 */
            ratingCount: number;
            reviewed: boolean;
            stable: boolean;
            stableRequest: boolean;
            tags: string[];
            /** Format: date-time */
            updated: string;
            /** Format: int32 */
            uploader: number;
        };
        Collection: {
            cover?: string | null;
            /** Format: date-time */
            created: string;
            description: string;
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            likes: number;
            name: string;
            /** Format: int32 */
            owner: number;
            public: boolean;
            /** Format: date-time */
            updated: string;
        };
        CollectionContent: {
            charts: number[];
            description: string;
            name: string;
            public: boolean;
        };
        DetailedCollection: components["schemas"]["Collection"] & {
            charts: components["schemas"]["ChartView"][];
        };
        DetailedUserView: components["schemas"]["UserView"] & {
            email?: string | null;
            /** Format: int64 */
            hykb_uid?: number | null;
        };
        EditP: {
            avatar?: string | null;
            bio?: string | null;
            char?: string | null;
            language?: string | null;
            name?: string | null;
        };
        EditPasswordP: {
            new: string;
            old: string;
        };
        EditR: {
            /** Format: date-time */
            chartUpdated: string;
            /** Format: date-time */
            updated: string;
        };
        EmailSub: {
            review: boolean;
            stb: boolean;
        };
        FollowP: {
            follow: boolean;
        };
        GetLikeR: {
            like: boolean;
        };
        GetPoolR: {
            bestPool: components["schemas"]["PoolItem"][];
            recentPool: components["schemas"]["PoolItem"][];
            /** Format: double */
            rks: number;
        };
        GetUserR: components["schemas"]["UserView"] & {
            following: boolean;
        };
        HideP: {
            hide: boolean;
        };
        HistoryItem: {
            approve?: boolean | null;
            /** Format: int32 */
            chart: number;
            comment?: string | null;
            /** Format: int32 */
            reviewer?: number | null;
            reviewerAvatar?: string | null;
            reviewerName?: string | null;
            /** Format: date-time */
            time: string;
        };
        Leaderboard: {
            reviewers: components["schemas"]["ReviewerStat"][];
        };
        LikeP: {
            like: boolean;
        };
        LikeR: {
            /** Format: int32 */
            likes: number;
        };
        List15R: components["schemas"]["RecordView"] & {
            /** Format: int32 */
            rank: number;
        };
        LoginP: {
            email: string;
            password: string;
        } | {
            refreshToken: string;
        };
        LoginR: {
            /** Format: date-time */
            expireAt: string;
            /** Format: int32 */
            id: number;
            refreshToken: string;
            token: string;
        };
        MyRatingR: {
            /** Format: int32 */
            id?: number | null;
            /** Format: int32 */
            score: number;
        };
        OAuthAppView: {
            avatar: string;
            clientId: string;
            /** Format: date-time */
            created: string;
            /** Format: int32 */
            creator: number;
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            maxPerm: number;
            name: string;
            redirectUri: string;
        };
        PaginationR_ChartView: {
            /** Format: int64 */
            count: number;
            results: {
                /** Format: date-time */
                chartUpdated: string;
                charter: string;
                composer: string;
                /** Format: date-time */
                created: string;
                description?: string | null;
                /** Format: float */
                difficulty: number;
                file: string;
                /** Format: int32 */
                id: number;
                illustration: string;
                illustrator: string;
                level: string;
                name: string;
                preview: string;
                ranked: boolean;
                /** Format: float */
                rating?: number | null;
                /** Format: int32 */
                ratingCount: number;
                reviewed: boolean;
                stable: boolean;
                stableRequest: boolean;
                tags: string[];
                /** Format: date-time */
                updated: string;
                /** Format: int32 */
                uploader: number;
            }[];
        };
        PaginationR_Collection: {
            /** Format: int64 */
            count: number;
            results: {
                cover?: string | null;
                /** Format: date-time */
                created: string;
                description: string;
                /** Format: int32 */
                id: number;
                /** Format: int32 */
                likes: number;
                name: string;
                /** Format: int32 */
                owner: number;
                public: boolean;
                /** Format: date-time */
                updated: string;
            }[];
        };
        PaginationR_QueryR: {
            /** Format: int64 */
            count: number;
            results: (components["schemas"]["RecordView"] & {
                playerAvatar?: string | null;
                playerBadges?: string[] | null;
                playerName?: string | null;
            })[];
        };
        PaginationR_StableRequestR: {
            /** Format: int64 */
            count: number;
            results: {
                approvedBy: string[];
                chart: components["schemas"]["ChartView"];
                deniedBy: string[];
                status: components["schemas"]["StableStatus"];
            }[];
        };
        PaginationR_UserView: {
            /** Format: int64 */
            count: number;
            results: {
                avatar?: string | null;
                badges: string[];
                banned: boolean;
                bio?: string | null;
                /** Format: int64 */
                exp: number;
                /** Format: int64 */
                follower_count: number;
                /** Format: int64 */
                following_count: number;
                /** Format: int32 */
                id: number;
                /** Format: date-time */
                joined: string;
                language: string;
                /** Format: date-time */
                last_login: string;
                login_banned: boolean;
                name: string;
                /** Format: float */
                rks: number;
                /** Format: int32 */
                roles: number;
            }[];
        };
        PatchP: {
            set: number[];
        } | {
            public: boolean;
        } | {
            /** Format: int32 */
            cover: number;
        };
        PoolItem: {
            /** Format: int32 */
            chart: number;
            /** Format: int32 */
            record: number;
            /** Format: double */
            rks: number;
        };
        PutP: components["schemas"]["CollectionContent"] & {
            /** Format: date-time */
            updated?: string | null;
        };
        QueryR: components["schemas"]["RecordView"] & {
            playerAvatar?: string | null;
            playerBadges?: string[] | null;
            playerName?: string | null;
        };
        QueueStatus: {
            /** Format: int64 */
            underReview: number;
            /** Format: int64 */
            unreviewed: number;
        };
        RateP: {
            /** Format: int32 */
            score: number;
        };
        RecordView: {
            /** Format: float */
            accuracy: number;
            /** Format: int32 */
            bad: number;
            best: boolean;
            best_std: boolean;
            /** Format: int32 */
            chart: number;
            full_combo: boolean;
            /** Format: int32 */
            good: number;
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            max_combo: number;
            /** Format: int32 */
            miss: number;
            /** Format: int32 */
            mods: number;
            /** Format: int32 */
            perfect: number;
            /** Format: int32 */
            player: number;
            /** Format: int32 */
            score: number;
            /** Format: float */
            speed: number;
            /** Format: float */
            std?: number | null;
            /** Format: float */
            std_score?: number | null;
            /** Format: date-time */
            time: string;
        };
        RegisterP: {
            email: string;
            name: string;
            password: string;
        };
        RegisterR: {
            /** Format: date-time */
            expireAt: string;
        };
        RegistrationDay: {
            /** Format: date */
            date: string;
            /** Format: int64 */
            newUsers: number;
        };
        RegistrationSeries: {
            series: components["schemas"]["RegistrationDay"][];
        };
        ReportP: {
            reason: string;
        };
        ReviewerStat: {
            /** Format: int64 */
            approved: number;
            /** Format: int64 */
            denied: number;
            /** Format: int64 */
            total: number;
            /** Format: int32 */
            userId: number;
            userName: string;
        };
        RksUpdateR: {
            /** Format: double */
            rks: number;
        };
        SetRankedP: {
            ranked: boolean;
        };
        SimpleUser: {
            /** Format: int32 */
            id: number;
            name: string;
        };
        StabilizeHistory: {
            approve?: boolean | null;
            /** Format: int32 */
            chart: number;
            comment?: string | null;
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            reviewer: number;
            /** Format: date-time */
            time: string;
        };
        StabilizeProfile: {
            /** Format: int64 */
            actionCount: number;
            /** Format: int64 */
            approvalCount: number;
            /** Format: int64 */
            messageWordCount: number;
            recentAction: components["schemas"]["StabilizeHistory"][];
            /** Format: int32 */
            userId: number;
            userName: string;
        };
        StabilizeProfileAll: components["schemas"]["StabilizeProfile"][];
        StableRequestR: {
            approvedBy: string[];
            chart: components["schemas"]["ChartView"];
            deniedBy: string[];
            status: components["schemas"]["StableStatus"];
        };
        /** @enum {string} */
        StableStatus: "pending" | "approved";
        StaffR: {
            admins: number[];
            headReviewers: number[];
            headSupervisors: number[];
            reviewers: number[];
            supervisors: number[];
        };
        StbStatusP: {
            approves: components["schemas"]["SimpleUser"][];
            denies: components["schemas"]["SimpleUser"][];
            history: components["schemas"]["HistoryItem"][];
            stable: boolean;
            stableRequest: boolean;
        };
        SupervisorStat: {
            /** Format: int64 */
            approved: number;
            /** Format: int64 */
            commentWordCount: number;
            /** Format: int64 */
            denied: number;
            /** Format: int64 */
            total: number;
            /** Format: int32 */
            userId: number;
            userName: string;
        };
        ThroughputDay: {
            /** Format: date */
            date: string;
            /** Format: int64 */
            denied: number;
            /** Format: int64 */
            passed: number;
        };
        ThroughputSeries: {
            series: components["schemas"]["ThroughputDay"][];
        };
        TokenR: {
            accessToken: string;
            /** Format: int64 */
            expiresIn: number;
            refreshToken: string;
            tokenType: string;
        };
        UpdateRolesP: {
            /** Format: int32 */
            add?: number;
            /** Format: int32 */
            remove?: number;
        };
        UploadR: {
            /** Format: date-time */
            expireAt: string;
            id: string;
        };
        UserStats: {
            /** Format: double */
            avgAccuracy: number;
            /** Format: int64 */
            numRecords: number;
        };
        UserView: {
            avatar?: string | null;
            badges: string[];
            banned: boolean;
            bio?: string | null;
            /** Format: int64 */
            exp: number;
            /** Format: int64 */
            follower_count: number;
            /** Format: int64 */
            following_count: number;
            /** Format: int32 */
            id: number;
            /** Format: date-time */
            joined: string;
            language: string;
            /** Format: date-time */
            last_login: string;
            login_banned: boolean;
            name: string;
            /** Format: float */
            rks: number;
            /** Format: int32 */
            roles: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    censor_detail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CensorRenderedP"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CensorBlock"][];
                };
            };
        };
    };
    chart_list: {
        parameters: {
            query?: {
                page?: number;
                pageNum?: number;
                search?: string;
                order?: string;
                tags?: string;
                filters?: Record<string, never>;
                /** @description Filter by uploader user id (captured into the filters map) */
                uploader?: number;
                /** @description Filter by review status */
                reviewed?: boolean;
                /** @description Filter by stable status */
                stable?: boolean;
                /** @description Filter by ranked status */
                ranked?: boolean;
                /** @description Filter by stable-request status */
                stableRequest?: boolean;
                /** @description Division tag */
                division?: string;
                /** @description Rating range as "lower,upper" (in tenths, e.g. 0.3,1.0) */
                rating?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginationR_ChartView"];
                };
            };
        };
    };
    chart_multi_get: {
        parameters: {
            query: {
                ids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartView"][];
                };
            };
        };
    };
    stable_requests: {
        parameters: {
            query?: {
                page?: number;
                pageNum?: number;
                search?: string;
                order?: string;
                tags?: string;
                filters?: Record<string, never>;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginationR_StableRequestR"];
                };
            };
        };
    };
    chart_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chart ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartView"];
                };
            };
        };
    };
    delete_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chart ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chart_edit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chart ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditP"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditR"];
                };
            };
        };
    };
    censor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chart ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CensorP"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    hide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chart ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HideP"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    my_rating: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chart ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyRatingR"];
                };
            };
        };
    };
    rate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chart ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateP"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_ranked: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chart ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRankedP"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stabilize_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chart ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StbStatusP"];
                };
            };
        };
    };
    collection_list: {
        parameters: {
            query?: {
                page?: number;
                pageNum?: number;
                search?: string;
                order?: string;
                tags?: string;
                filters?: Record<string, never>;
                /** @description Filter by owner user id (captured into the filters map) */
                owner?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginationR_Collection"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionContent"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedCollection"];
                };
            };
        };
    };
    collection_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedCollection"];
                };
            };
        };
    };
    put_collection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutP"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedCollection"];
                };
            };
        };
    };
    delete_collection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_collection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchP"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedCollection"];
                };
            };
        };
    };
    get_like_collection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetLikeR"];
                };
            };
        };
    };
    like_collection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LikeP"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeR"];
                };
            };
        };
    };
    report_collection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportP"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dash_reviews_leaderboard: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Leaderboard"];
                };
            };
        };
    };
    queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueStatus"];
                };
            };
        };
    };
    dash_reviews_throughput: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThroughputSeries"];
                };
            };
        };
    };
    dash_stables_leaderboard: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Leaderboard"];
                };
            };
        };
    };
    profile_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StabilizeProfileAll"];
                };
            };
        };
    };
    dash_stables_throughput: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThroughputSeries"];
                };
            };
        };
    };
    profile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Supervisor user ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StabilizeProfile"];
                };
            };
        };
    };
    active: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveSeries"];
                };
            };
        };
    };
    registration: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationSeries"];
                };
            };
        };
    };
    edit_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditPasswordP"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginP"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginR"];
                };
            };
            /** @description login failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedUserView"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    user_edit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditP"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_char: {
        parameters: {
            query?: {
                locale?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"];
                };
            };
        };
    };
    get_chars: {
        parameters: {
            query?: {
                locale?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"][];
                };
            };
        };
    };
    get_subs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailSub"];
                };
            };
        };
    };
    edit_subs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailSub"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authorize: {
        parameters: {
            query: {
                response_type: string;
                client_id: string;
                redirect_uri?: string;
                scope?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizeR"];
                };
            };
        };
    };
    get_token: {
        parameters: {
            query: {
                grant_type: string;
                code: string;
                redirect_uri?: string;
                client_id: string;
                client_secret: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenR"];
                };
            };
        };
    };
    get_app: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description OAuth client ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthAppView"];
                };
            };
        };
    };
    record_list: {
        parameters: {
            query?: {
                page?: number;
                pageNum?: number;
                search?: string;
                order?: string;
                tags?: string;
                filters?: Record<string, never>;
                /** @description Filter by player user id (captured into the filters map) */
                player?: number;
                /** @description Filter by chart id (captured into the filters map) */
                chart?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordView"][];
                };
            };
        };
    };
    best: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chart ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BestR"];
                };
            };
        };
    };
    get_pool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Player ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPoolR"];
                };
            };
        };
    };
    list15: {
        parameters: {
            query?: {
                std?: boolean;
            };
            header?: never;
            path: {
                /** @description Chart ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List15R"][];
                };
            };
        };
    };
    record_multi_get: {
        parameters: {
            query: {
                ids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordView"][];
                };
            };
        };
    };
    query: {
        parameters: {
            query?: {
                includePlayer?: boolean;
                std?: boolean;
                page?: number;
                pageNum?: number;
            };
            header?: never;
            path: {
                /** @description Chart ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginationR_QueryR"];
                };
            };
        };
    };
    rks_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Player ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RksUpdateR"];
                };
            };
        };
    };
    record_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Record ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordView"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterP"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterR"];
                };
            };
        };
    };
    staff: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffR"];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Original file name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": number[];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadR"];
                };
            };
        };
    };
    user_list: {
        parameters: {
            query?: {
                /** @description Filter users by name (case-insensitive substring) */
                search?: string;
                /** @description Filter users this user follows */
                following?: number;
                /** @description Filter followers of this user */
                followedBy?: number;
                /** @description Cursor: only return users with id >= this value */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginationR_UserView"];
                };
            };
        };
    };
    get_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUserR"];
                };
            };
        };
    };
    ban_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ban_avatar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ban_user_login: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    follow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowP"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    report_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportP"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    user_stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStats"];
                };
            };
        };
    };
    update_roles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRolesP"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
